### PR TITLE
Add link to 'Universal Hex Separator' to the Universal Hex Tool page

### PR DESCRIPTION
**Pull request by microbit-carlos**

### CODE REVIEW

**Comment by jaustin** [comment]
I'm happy with this. Ideally it might be good to get 'splitter' in there for Googleability but I can't necessarily tell you why 'separator' and splitter' seem different

**Comment by microbit-carlos** [comment]
@microbit-robert this is ready to be merged when you get a chance.

**Comment by microbit-carlos** [comment]
Friendly ping @microbit-robert :)

**Review by microbit-robert — APPROVED** [review]
LGTM.

**Pull request merged**
