### PR TITLE
Add Creative Commons CC-BY-SA 4.0 license

### PR DESCRIPTION
**Pull request by microbit-mark**
As per #92 we would like to add a [Creative Commons BY SA 4.0 license](https://creativecommons.org/licenses/by-sa/4.0/) and seek retrospective approval for content in this repository from the following contributors. If your user is listed, please add a comment with a 👍 or a few words which will be considered explicit approval. Any questions, please raise these in the comments.

- [x] @themarkness 
- [x] @carlosperate 
- [x] @merwok 
- [x] @mike-eason 
- [x] @medishield 
- [x] @jimmo
- [x] @SaitoYutaka 
- [x] @CleoQc 
- [ ] @chainjazz 
- [ ] @markfirmware 
- [x] @mikini

### CODE REVIEW

**Comment by themarkness** [comment]
👍 Fine for me

**Comment by carlosperate** [comment]
👍 I agree to retroactively apply the Creative Commons BY SA 4.0 license to all contributions to this repository.

**Comment by merwok** [comment]
I thought my changes were trivial, but I agree to the licensing change :+1:

**Comment by mikini** [comment]
Splendid idea. I too agree to retrospectively apply the CC BY-SA 4.0 license to my contributions to the microbit-foundation/dev-docs repository.

**Comment by mike-eason** [comment]
Fine by me, thank you. 👍

**Comment by microbit-mark** [comment]
Just pinging this issue again to see if you would be able to approve your contributions to have a Creative Commons license applied @medishield @SaitoYutaka @chainjazz @markfirmware 

Please reply if you are able

**Comment by SaitoYutaka** [comment]
Fine by me. 👍

**Comment by microbit-mark** [comment]
Just pinging this issue again to see if you would be able to approve your contributions to have a Creative Commons license applied @chainjazz @medishield @markfirmware 

If we don't hear back, in order to progress this change we will work on the basis that you do not approve and will need to remove your contribution.

**Comment by medishield** [comment]
@microbit-mark: sorry for the late reply. I approve. Thanks.

**Comment by microbit-mark** [comment]
We're now in a position to add the license and we have reverted two commits from those who were unable to respond:
https://github.com/microbit-foundation/dev-docs/commit/fe323558c74a6369475d86137e81ab259426fe93 and
https://github.com/microbit-foundation/dev-docs/commit/b33b21cdabf432c85bb9ddffb773e37dc2ddb6c7

Thanks for the feedback and your fantastic contributions everyone. 🎆 👏

**Pull request merged**
