### PR TITLE
merge edge connector pages

### PR DESCRIPTION
**Pull request by microbit-mark**
http://review.review.tech.microbit.org.s3-website-eu-west-1.amazonaws.com/hardware/edgeconnector/

as per #94 an example of the pages merged

### CODE REVIEW

**Comment by jaustin** [comment]
From the diff I think this looks about right - Is it possible for you to make a review branch of the tech site with this PR? I think it'll be much easier to judge the effectiveness of merging these pages if we've done that.

**Comment by microbit-mark** [comment]
added link to review branch

**Comment by jaustin** [comment]
We should leave a link to the new combined page on the old one - for now a simple 'page has moved' would work, but redirect would be nice too.

**Comment by microbit-mark** [comment]
Good plan. Forgot people might link to it I've added the old datasheet page back with a note for now and we can add a redirect at the same time we deploy the site with the changes

**Comment by microbit-mark** [comment]
Add TOC and move third party edge connector above further info

**Pull request merged**
