### PR TITLE
add alternative connnector to page

### LINKED ISSUE #91: Add info about edge connectors and suppliers
We should add info and contact details for edge connector manufacturers to https://tech.microbit.org/hardware/edgeconnector/

Requested by @James-Guo-cylconn via @halspeed

### PR DESCRIPTION
**Pull request by microbit-mark**
Add a table that renders like this

screenshot 2018-12-13 at 13 51 25

closes #91

### CODE REVIEW

**Comment by James-Guo-cylconn** [comment]
Thanks so much Mark, the Christmas is coming.
Hope you and your respectable are preparing and enjoy it.

Good luck
James

**Comment by microbit-mark** [comment]
Add Edit this page icon/URl to section

**Comment by James-Guo-cylconn** [comment]
Mark,sorry,do not know how to edit and where to edit.

**Comment by James-Guo-cylconn** [comment]
Are you going to start the Christmas and new year holiday?
 If you have time,could help link them to the icon and items?
http://www.dgyuliang.net/html/281.html
http://www.dgyuliang.net/html/280.html
Thanks a lot and wish you enjoy the holiday soon.
James

**Pull request merged**
